// Generated by tools/generate_brand.py; do not edit.

/// Side of the icon's pixel grid.
pub(crate) const ICON_GRID: usize = 16;

/// RGBA colours for grid indices 1..; index 0 is transparent.
pub(crate) const ICON_PALETTE: [[u8; 4]; 4] = [
    [20, 17, 46, 255],
    [63, 55, 168, 255],
    [124, 108, 255, 255],
    [255, 201, 51, 255],
];

/// One ASCII digit per pixel, row by row: an index into the palette plus one.
pub(crate) const ICON_PIXELS: [[u8; 16]; 16] = [
    *b"0011111111111100",
    *b"0111111111111110",
    *b"1111111111111111",
    *b"1111111111111111",
    *b"1122233344441111",
    *b"1122333444444111",
    *b"1122334444444411",
    *b"1122334444444411",
    *b"1122334444444411",
    *b"1122334444444411",
    *b"1122333444444111",
    *b"1122233344441111",
    *b"1111111111111111",
    *b"1111111111111111",
    *b"0111111111111110",
    *b"0011111111111100",
];
