fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    // `gaanim` links the engine library and Rust's `std` dynamically. An
    // installation ships both next to the executable; a build run from
    // `target/` finds `std` in the toolchain that compiled it.
    let toolchain_libs = std::process::Command::new(std::env::var("RUSTC").unwrap())
        .args(["--print", "target-libdir", "--target"])
        .arg(std::env::var("TARGET").unwrap())
        .output()
        .ok()
        .filter(|output| output.status.success())
        .map(|output| String::from_utf8_lossy(&output.stdout).trim().to_string());
    let origin = match std::env::var("CARGO_CFG_TARGET_OS").as_deref() {
        Ok("linux") => Some("$ORIGIN"),
        Ok("macos") => Some("@executable_path"),
        _ => None,
    };
    if let Some(origin) = origin {
        println!("cargo:rustc-link-arg-bins=-Wl,-rpath,{origin}");
        if let Some(libs) = toolchain_libs {
            println!("cargo:rustc-link-arg-bins=-Wl,-rpath,{libs}");
        }
    }

    // Embed the Gaanim icon so `gaanim.exe` shows it in Explorer. MSVC link and
    // lld-link take the .res generated by tools/generate_brand.py as an input.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows")
        && std::env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("msvc")
    {
        let res = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../docs/assets/brand/gaanim-app.res");
        println!("cargo:rerun-if-changed={}", res.display());
        println!("cargo:rustc-link-arg-bins={}", res.display());
    }
}
