fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    // Embed the Gaanim icon so `gaanim.exe` shows it in Explorer. MSVC link and
    // lld-link take the .res generated by tools/generate_brand.py as an input.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows")
        && std::env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("msvc")
    {
        let res = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../docs/assets/brand/gaanim-app.res");
        println!("cargo:rerun-if-changed={}", res.display());
        println!("cargo:rustc-link-arg-bins={}", res.display());
    }
}
