[package]
name = "gaanim_python"
version = "0.2.0"
edition = "2021"

[lib]
name = "gaanim_python"
crate-type = ["rlib"]

[dependencies]
pyo3 = { version = "0.28", features = ["abi3-py312", "multiple-pymethods", "py-clone"] }
gaanim_core = { path = "../gaanim_core" }
gaanim_api = { path = "../gaanim_api" }
gaanim_animation = { path = "../gaanim_animation" }
gaanim_math = { path = "../gaanim_math" }
gaanim_layout = { path = "../gaanim_layout" }
gaanim_objects = { path = "../gaanim_objects" }
gaanim_scene = { path = "../gaanim_scene" }
gaanim_text = { path = "../gaanim_text" }
gaanim_timeline = { path = "../gaanim_timeline" }
gaanim_visualization = { path = "../gaanim_visualization" }
