"""Gaanim — GPU-accelerated vector animation engine."""

import warnings

from . import colors
from .gaanim_core import (
    Anchor,
    AnchorPoint,
    Direction,
    Layout,
    LayoutItem,
    LayoutExpression,
    LayoutConstraint,
    ConstraintSet,
    LayoutOwnershipError,
    BLACK,
    BLUE,
    CORAL,
    CYAN,
    GOLD,
    GRAY,
    GREEN,
    NAVY,
    ORANGE,
    PINK,
    PURPLE,
    RED,
    TEAL,
    WHITE,
    YELLOW,
    Anim,
    Color,
    Brush,
    Camera,
    Theme,
    Style,
    StrokeStyle,
    AxesStyle,
    Drawable,
    Dimension,
    Material3D,
    Primitive3D,
    Text,
    TextPart,
    TextStyle,
    TextFlow,
    TextSelection,
    TextQuery,
    part,
    Transition,
    Updater,
    Axis,
    Parameter,
    Readout,
    Variable,
    CoordinateRef,
    CoordinateSpace,
    CoordinateSpace3D,
    NumberLine,
    PolarSpace,
    DataTable,
    DataSource,
    Scene,
    Segment,
)
from .templates import (
    LayoutTemplate,
    comparison,
    credits,
    layout_template,
    lecture,
    lower_third,
    minimal,
    title_slide,
    vertical_short,
)


def Canvas(*args, **kwargs):
    """Deprecated compatibility constructor; use :class:`Scene` instead."""
    warnings.warn(
        "Canvas is deprecated as the animation facade; use Scene instead. "
        "Use scene.canvas for viewport configuration.",
        DeprecationWarning,
        stacklevel=2,
    )
    return Scene(*args, **kwargs)


__all__ = [
    "Scene",
    "Segment",
    "Canvas",
    "Drawable",
    "Dimension",
    "Material3D",
    "Primitive3D",
    "Text",
    "TextPart",
    "TextStyle",
    "TextFlow",
    "TextSelection",
    "TextQuery",
    "part",
    "Anim",
    "Transition",
    "Color",
    "Brush",
    "Camera",
    "Theme",
    "Style",
    "StrokeStyle",
    "AxesStyle",
    "colors",
    "Anchor",
    "AnchorPoint",
    "Direction",
    "Layout",
    "LayoutItem",
    "LayoutExpression",
    "LayoutConstraint",
    "ConstraintSet",
    "LayoutOwnershipError",
    "LayoutTemplate",
    "layout_template",
    "title_slide",
    "lecture",
    "comparison",
    "vertical_short",
    "minimal",
    "lower_third",
    "credits",
    "Updater",
    "Axis",
    "Parameter",
    "Readout",
    "Variable",
    "CoordinateRef",
    "CoordinateSpace",
    "CoordinateSpace3D",
    "NumberLine",
    "PolarSpace",
    "DataTable",
    "DataSource",
    "GOLD",
    "CORAL",
    "BLUE",
    "WHITE",
    "BLACK",
    "RED",
    "GREEN",
    "YELLOW",
    "ORANGE",
    "PURPLE",
    "PINK",
    "GRAY",
    "CYAN",
    "NAVY",
    "TEAL",
]

# Explicitly expose the traced numeric helpers as ``gaanim.math``.
from . import math

__version__ = "0.1.0"
