"""Gaanim — GPU-accelerated vector animation engine."""

import sys
import warnings

if f"{__name__}.gaanim_core" not in sys.modules:
    raise RuntimeError(
        "The `gaanim` wheel only provides authoring helpers and type information. "
        "Run animation scripts with `gaanim <script.py>` or open them in the Gaanim editor."
    )

from . import colors
from .gaanim_core import (
    Anchor,
    AnchorPoint,
    PointRef,
    Direction,
    Layout,
    LayoutItem,
    LayoutExpression,
    LayoutConstraint,
    ConstraintSet,
    LayoutOwnershipError,
    BLACK,
    BLUE,
    CORAL,
    CYAN,
    GOLD,
    GRAY,
    GREEN,
    NAVY,
    ORANGE,
    PINK,
    PURPLE,
    RED,
    TEAL,
    WHITE,
    YELLOW,
    Anim,
    Color,
    Brush,
    Background,
    Camera,
    CameraConstraint,
    Theme,
    Style,
    StrokeStyle,
    AxesStyle,
    Drawable,
    Dimension,
    AngleDimension,
    ForceVector,
    Support,
    SurroundingRect,
    Material3D,
    Primitive3D,
    Text,
    TextAnchor,
    TextPart,
    TextParts,
    TextStyle,
    TextFlow,
    TextSelection,
    TextQuery,
    part,
    parts,
    Transition,
    Updater,
    Axis,
    Scale,
    Field,
    Value,
    Guide,
    ChartSpec,
    Chart,
    Parameter,
    Readout,
    Variable,
    CoordinateRef,
    CoordinateSpace,
    CoordinateSpace3D,
    Cartesian2D,
    Cartesian3D,
    NumberLine,
    PolarSpace,
    DataTable,
    DataSource,
    Scene,
    Segment,
)

# Keep the semantic complex-space name available even when an embedding host
# has an older abi3 module already loaded in-process.
ComplexSpace = CoordinateSpace
from .templates import (
    LayoutTemplate,
    comparison,
    credits,
    layout_template,
    lecture,
    lower_third,
    minimal,
    title_slide,
    vertical_short,
)
from .composition import AnimationGroup, LaggedStart, Succession
from .matrix import (
    Matrix,
    MatrixAlgebraError,
    MatrixDerivation,
    MatrixEntry,
    MatrixSelection,
    MatrixSelectionAnimation,
    MatrixStep,
)


def Canvas(*args, **kwargs):
    """Deprecated compatibility constructor; use :class:`Scene` instead."""
    warnings.warn(
        "Canvas is deprecated as the animation facade; use Scene instead. "
        "Use scene.canvas for viewport configuration.",
        DeprecationWarning,
        stacklevel=2,
    )
    return Scene(*args, **kwargs)


__all__ = [
    "Scene",
    "Segment",
    "Canvas",
    "AnimationGroup",
    "LaggedStart",
    "Succession",
    "Matrix",
    "MatrixEntry",
    "MatrixSelection",
    "MatrixSelectionAnimation",
    "MatrixStep",
    "MatrixDerivation",
    "MatrixAlgebraError",
    "Drawable",
    "Dimension",
    "AngleDimension",
    "ForceVector",
    "Support",
    "SurroundingRect",
    "Material3D",
    "Primitive3D",
    "Text",
    "TextAnchor",
    "TextPart",
    "TextParts",
    "TextStyle",
    "TextFlow",
    "TextSelection",
    "TextQuery",
    "part",
    "parts",
    "Anim",
    "Transition",
    "Color",
    "Brush",
    "Background",
    "Camera",
    "CameraConstraint",
    "Theme",
    "Style",
    "StrokeStyle",
    "AxesStyle",
    "colors",
    "Anchor",
    "AnchorPoint",
    "PointRef",
    "Direction",
    "Layout",
    "LayoutItem",
    "LayoutExpression",
    "LayoutConstraint",
    "ConstraintSet",
    "LayoutOwnershipError",
    "LayoutTemplate",
    "layout_template",
    "title_slide",
    "lecture",
    "comparison",
    "vertical_short",
    "minimal",
    "lower_third",
    "credits",
    "Updater",
    "Axis",
    "Scale",
    "Field",
    "Value",
    "Guide",
    "ChartSpec",
    "Chart",
    "Parameter",
    "Readout",
    "Variable",
    "CoordinateRef",
    "CoordinateSpace",
    "CoordinateSpace3D",
    "Cartesian2D",
    "Cartesian3D",
    "ComplexSpace",
    "NumberLine",
    "PolarSpace",
    "DataTable",
    "DataSource",
    "GOLD",
    "CORAL",
    "BLUE",
    "WHITE",
    "BLACK",
    "RED",
    "GREEN",
    "YELLOW",
    "ORANGE",
    "PURPLE",
    "PINK",
    "GRAY",
    "CYAN",
    "NAVY",
    "TEAL",
]

# Explicitly expose the traced numeric helpers as ``gaanim.math``.
from . import math

__version__ = "0.1.0"
