from __future__ import annotations

from typing import Optional, Sequence

class Color:
    def __init__(self, r: int, g: int, b: int, a: int = 255) -> None: ...

class Transition:
    @staticmethod
    def cut() -> Transition: ...
    @staticmethod
    def cross_fade(duration: float) -> Transition: ...
    @staticmethod
    def fade_through(duration: float, color: Color) -> Transition: ...
    @staticmethod
    def slide(duration: float, direction: str) -> Transition: ...

class Anim:
    def duration(self, d: float) -> Anim: ...
    def ease(self, name: str) -> Anim: ...
    def rate(self, name: str) -> Anim: ...
    def delay(self, sec: float) -> Anim: ...
    def steps(self, n: int) -> Anim: ...
    def spring(self) -> Anim: ...
    def smooth(self) -> Anim: ...
    def linear(self) -> Anim: ...

class Drawable:
    def fill(self, color: Color) -> Drawable: ...
    def no_fill(self) -> Drawable: ...
    def stroke(self, color: Color, width: float) -> Drawable: ...
    def no_stroke(self) -> Drawable: ...
    def opacity(self, op: float) -> Drawable: ...
    def z_index(self, z: int) -> Drawable: ...
    def at(self, x: float, y: float) -> Drawable: ...
    def move(self, dx: float, dy: float) -> Anim: ...
    def move_to(self, x: float, y: float) -> Anim: ...
    def glide_to(self, x: float, y: float) -> Anim: ...
    def scale(self, factor: float) -> Anim: ...
    def rotate(self, rad: float) -> Anim: ...
    def fade_in(self) -> Anim: ...
    def fade_out(self) -> Anim: ...
    def fade_to(self, alpha: float) -> Anim: ...
    def write(self) -> Anim: ...
    def create(self) -> Anim: ...
    def unwrite(self) -> Anim: ...
    def uncreate(self) -> Anim: ...
    def grow_from_center(self) -> Anim: ...
    def shrink_to_center(self) -> Anim: ...
    def spin_in_from_nothing(self) -> Anim: ...
    def draw_border_then_fill(self) -> Anim: ...
    def indicate(self) -> Anim: ...
    def wiggle(self) -> Anim: ...

class Canvas:
    def __init__(
        self,
        width: int = 1280,
        height: int = 720,
        background: Optional[Color] = None,
    ) -> None: ...
    def circle(self, r: float) -> Drawable: ...
    def rect(self, w: float, h: float) -> Drawable: ...
    def rounded_rect(self, w: float, h: float, r: float) -> Drawable: ...
    def square(self, s: float) -> Drawable: ...
    def dot(self, r: float) -> Drawable: ...
    def ellipse(self, rx: float, ry: float) -> Drawable: ...
    def line(self, x1: float, y1: float, x2: float, y2: float) -> Drawable: ...
    def arrow(self, x1: float, y1: float, x2: float, y2: float) -> Drawable: ...
    def text(self, s: str) -> Drawable: ...
    def title(self, s: str) -> Drawable: ...
    def subtitle(self, s: str) -> Drawable: ...
    def equation(self, s: str) -> Drawable: ...
    def group(self, members: Sequence[Drawable]) -> Drawable: ...
    def segment(self, name: str, transition: Optional[Transition] = None) -> int: ...
    def link(self, from_: int, to: int, transition: Transition) -> None: ...
    def wait(self, d: float) -> None: ...
    def play(self, anims: Sequence[Anim]) -> None: ...
    def slide(self) -> None: ...
    def fade_out_all(self, d: float) -> None: ...
    def render(self) -> None: ...
    def export(self, path: str, fps: Optional[int] = None) -> None: ...

GOLD: Color
CORAL: Color
BLUE: Color
WHITE: Color
BLACK: Color
RED: Color
GREEN: Color
YELLOW: Color
ORANGE: Color
PURPLE: Color
PINK: Color
GRAY: Color
CYAN: Color
NAVY: Color
TEAL: Color
