from __future__ import annotations

from typing import Callable, ClassVar, Literal, Optional, Sequence, TypeAlias

CurvePoint: TypeAlias = tuple[float, float]
"""A coordinate pair used by :meth:`Scene.curve`."""

CurveControl: TypeAlias = CurvePoint | Literal["auto"] | None
"""A Bézier control point, an automatically reflected handle, or a collapsed handle."""

CurveCommand: TypeAlias = tuple[str, Sequence[CurvePoint | CurveControl]]
"""A ``Scene.curve`` command and its arguments."""

class Color:
    def __init__(self, r: int, g: int, b: int, a: int = 255) -> None: ...

class Anchor:
    CENTER: ClassVar[Anchor]
    TOP: ClassVar[Anchor]
    BOTTOM: ClassVar[Anchor]
    LEFT: ClassVar[Anchor]
    RIGHT: ClassVar[Anchor]
    TOP_LEFT: ClassVar[Anchor]
    TOP_RIGHT: ClassVar[Anchor]
    BOTTOM_LEFT: ClassVar[Anchor]
    BOTTOM_RIGHT: ClassVar[Anchor]

class Direction:
    UP: ClassVar[Direction]
    DOWN: ClassVar[Direction]
    LEFT: ClassVar[Direction]
    RIGHT: ClassVar[Direction]
    UP_LEFT: ClassVar[Direction]
    UP_RIGHT: ClassVar[Direction]
    DOWN_LEFT: ClassVar[Direction]
    DOWN_RIGHT: ClassVar[Direction]
    @staticmethod
    def custom(x: float, y: float, z: float = 0.0) -> Direction: ...

class LayoutRegion:
    width: float
    height: float
    def place(self, drawable: Drawable, anchor: Anchor) -> Drawable: ...
    def point(self, anchor: Anchor) -> tuple[float, float]: ...
    def inset(
        self,
        value: float,
        right: Optional[float] = None,
        bottom: Optional[float] = None,
        left: Optional[float] = None,
    ) -> LayoutRegion: ...
    def grid(
        self,
        rows: int = 1,
        columns: int = 1,
        row_gap: float = 0.0,
        column_gap: float = 0.0,
    ) -> GridLayout: ...
    def grid_tracks(
        self,
        rows: Sequence[float | str],
        columns: Sequence[float | str],
        row_gap: float = 0.0,
        column_gap: float = 0.0,
    ) -> GridLayout: ...

class GridLayout:
    rows: int
    columns: int
    def cell(self, row: int, column: int) -> LayoutRegion: ...
    def area(
        self,
        row: int,
        column: int,
        row_span: int = 1,
        column_span: int = 1,
    ) -> LayoutRegion: ...

class FrameLayout:
    frame: LayoutRegion
    header: LayoutRegion
    content: LayoutRegion
    footer: LayoutRegion
    def column(self, index: int, count: int = 2, gap: float = 24.0) -> LayoutRegion: ...

class Flow:
    count: int
    def add(self, drawable: Drawable) -> None: ...
    def build(self) -> Drawable: ...

class Transition:
    @staticmethod
    def cut() -> Transition: ...
    @staticmethod
    def cross_fade(duration: float) -> Transition: ...
    @staticmethod
    def fade_through(duration: float, color: Color) -> Transition: ...
    @staticmethod
    def slide(duration: float, direction: str) -> Transition: ...
    @staticmethod
    def zoom_through(
        duration: float,
        *,
        center: tuple[float, float] = (0.0, 0.0),
        max_zoom: float = 4.0,
    ) -> Transition: ...

class Anim:
    def duration(self, d: float) -> Anim: ...
    def ease(self, name: str) -> Anim: ...
    def rate(self, name: str) -> Anim: ...
    def delay(self, sec: float) -> Anim: ...
    def steps(self, n: int) -> Anim: ...
    def spring(self) -> Anim: ...
    def smooth(self) -> Anim: ...
    def linear(self) -> Anim: ...
    def lag_ratio(self, value: float) -> Anim: ...
    def stroke_width(self, value: float) -> Anim: ...
    def with_pen_tip(self) -> Anim: ...

class Updater:
    """Preset updater — attach to a DrawableHandle via add_updater()."""
    @staticmethod
    def orbit(cx: float, cy: float, radius: float, speed: float) -> Updater: ...
    @staticmethod
    def advance_x(speed: float) -> Updater: ...
    @staticmethod
    def bob(amplitude: float, frequency: float) -> Updater: ...
    @staticmethod
    def rotate(speed: float) -> Updater: ...
    @staticmethod
    def pulse(min_scale: float, max_scale: float, frequency: float) -> Updater: ...

class Drawable:
    def fill(self, color: Color) -> Drawable: ...
    def no_fill(self) -> Drawable: ...
    def stroke(self, color: Color, width: float) -> Drawable: ...
    def no_stroke(self) -> Drawable: ...
    def color_by(self, fragment: str, color: Color) -> Drawable: ...
    def select(self, fragment: str, occurrence: Optional[int] = None) -> FragmentSelection: ...
    def tag(self, name: str) -> FragmentSelection: ...
    def indicate_tag(self, name: str, duration: Optional[float] = None) -> Drawable: ...
    def cancel_term(self, name: str, duration: Optional[float] = None) -> Drawable: ...
    def reveal_fragment(
        self,
        fragment: str,
        *,
        style: str = "fade",
        duration: Optional[float] = None,
        occurrence: Optional[int] = None,
    ) -> Drawable: ...
    def opacity(self, op: float) -> Drawable: ...
    def z_index(self, z: int) -> Drawable: ...
    def at(self, x: float, y: float) -> Drawable: ...
    def scaled(self, factor: float) -> Drawable: ...
    def rotated(self, radians: float) -> Drawable: ...
    def with_pivot(self, x: float, y: float) -> Drawable: ...
    def pivot(self, x: float, y: float) -> Drawable: ...
    def at_anchor(self, x: float, y: float, anchor: Anchor) -> Drawable: ...
    def next_to(
        self,
        reference: Drawable,
        direction: Direction,
        spacing: float = 24.0,
        aligned_edge: Optional[Anchor] = None,
    ) -> Drawable: ...
    def align_to(
        self,
        reference: Drawable,
        target_anchor: Anchor,
        reference_anchor: Optional[Anchor] = None,
    ) -> Drawable: ...
    def to_edge(self, direction: Direction, buff: float = 24.0) -> Drawable: ...
    def to_corner(self, corner: Anchor, buff: float = 24.0) -> Drawable: ...
    def vstack(self, gap: float = 24.0, align: Optional[Anchor] = None) -> Drawable: ...
    def hstack(self, gap: float = 24.0, align: Optional[Anchor] = None) -> Drawable: ...
    def move(self, dx: float, dy: float) -> Anim: ...
    def move_to(self, x: float, y: float) -> Anim: ...
    def glide_to(self, x: float, y: float) -> Anim: ...
    def scale(self, factor: float) -> Anim: ...
    def rotate(self, rad: float) -> Anim: ...
    def fade_in(self, duration: Optional[float] = None) -> Anim: ...
    def fade_in_from(
        self,
        direction: Direction,
        distance: float = 48.0,
        duration: Optional[float] = None,
    ) -> Anim: ...
    def fade_out(self, duration: Optional[float] = None) -> Anim: ...
    def fade_to(self, alpha: float) -> Anim: ...
    def write(self, duration: Optional[float] = None) -> Anim: ...
    def write_by_term(
        self,
        *,
        tags: Optional[Sequence[str]] = None,
        duration: float = 1.0,
    ) -> Drawable: ...
    def create(self, duration: Optional[float] = None) -> Anim: ...
    def unwrite(self, duration: Optional[float] = None) -> Anim: ...
    def uncreate(self, duration: Optional[float] = None) -> Anim: ...
    def grow_from_center(self, duration: Optional[float] = None) -> Anim: ...
    def shrink_to_center(self, duration: Optional[float] = None) -> Anim: ...
    def spin_in_from_nothing(self, duration: Optional[float] = None) -> Anim: ...
    def draw_border_then_fill(self, duration: Optional[float] = None) -> Anim: ...
    def indicate(self, duration: Optional[float] = None) -> Anim: ...
    def wiggle(self, duration: Optional[float] = None) -> Anim: ...
    def fade_transform(self, target: Drawable) -> Anim: ...
    def transform(self, target: Drawable) -> Anim: ...
    def replacement_transform(self, target: Drawable) -> Anim: ...
    # Reactive methods
    def add_updater(self, updater: Updater) -> None: ...
    def remove_updater(self) -> None: ...
    def bind_y_from(self, source: Drawable) -> None: ...
    def bind_x_from(self, source: Drawable) -> None: ...
    def attach_to(self, source: Drawable) -> None: ...
    def follow_to(self, source: Drawable, offset: tuple[float, float]) -> None: ...
    def bind_position_from(self, source: Drawable, axes: str = "xy") -> None: ...

class FragmentSelection:
    def fill(self, color: Color) -> FragmentSelection: ...
    def indicate(self, duration: Optional[float] = None) -> FragmentSelection: ...
    def reveal(self, style: str = "fade", duration: Optional[float] = None) -> FragmentSelection: ...
    def cancel(self, duration: Optional[float] = None) -> FragmentSelection: ...
    def color_to(self, color: Color, duration: Optional[float] = None) -> FragmentSelection: ...
    def transform_to(self, target: FragmentSelection, duration: Optional[float] = None) -> FragmentSelection: ...

class ValueTracker:
    current: float
    def get_value(self) -> float: ...
    def set_value(self, value: float) -> None: ...
    def animate_to(self, value: float) -> Anim: ...

class Canvas:
    """Visual viewport configuration owned by a Scene."""
    width: int
    height: int
    background: Optional[Color]
    def set_margin(self, margin: float) -> None: ...

class Scene:
    def __init__(
        self,
        width: int = 1280,
        height: int = 720,
        background: Optional[Color] = None,
        margin: Optional[float] = None,
    ) -> None: ...
    @property
    def canvas(self) -> Canvas: ...
    def layout(self, header: float = 0.0, footer: float = 0.0, gap: float = 24.0) -> FrameLayout: ...
    def layout_preset(
        self,
        name: Literal["lecture", "comparison", "vertical_short", "minimal"],
    ) -> FrameLayout: ...
    def flow(
        self,
        direction: Literal["vertical", "horizontal"] = "vertical",
        gap: float = 24.0,
        align: Optional[Anchor] = None,
    ) -> Flow: ...
    def circle(self, r: float) -> Drawable: ...
    def rect(self, w: float, h: float) -> Drawable: ...
    def rounded_rect(self, w: float, h: float, r: float) -> Drawable: ...
    def square(self, s: float) -> Drawable: ...
    def dot(self, r: float) -> Drawable: ...
    def ellipse(self, rx: float, ry: float) -> Drawable: ...
    def line(self, x1: float, y1: float, x2: float, y2: float) -> Drawable: ...
    def arrow(self, x1: float, y1: float, x2: float, y2: float) -> Drawable: ...
    def arc(self, cx: float, cy: float, radius: float, start_angle: float, sweep_angle: float) -> Drawable: ...
    def curved_arrow(self, x1: float, y1: float, x2: float, y2: float, angle: float) -> Drawable: ...
    def curved_arrow_arc(self, cx: float, cy: float, radius: float, start_angle: float, sweep_angle: float) -> Drawable: ...
    def dimension(self, x1: float, y1: float, x2: float, y2: float, offset: float) -> Drawable: ...
    def polyline(self, points: Sequence[tuple[float, float]]) -> Drawable: ...
    def bezier(self, start: tuple[float, float], controls: Sequence[tuple[float, float]], end: tuple[float, float]) -> Drawable: ...
    def curve(self, commands: Sequence[CurveCommand]) -> Drawable:
        """Create a composed curve from ``move``, ``line``, ``quad``, ``cubic``, and close commands.

        Append ``_rel`` to a drawing command to use cursor-relative points.
        Quadratic and cubic controls accept a point, ``None``, or ``"auto"``.
        Use ``close`` or ``close_smooth`` with an empty argument sequence.
        """
        ...
    def function_graph(self, function: Callable[[float], float], x: tuple[float, float], samples: int = 160) -> Drawable: ...
    def parametric_curve(self, function: Callable[[float], tuple[float, float]], t: tuple[float, float], samples: int = 240) -> Drawable: ...
    def axes(
        self,
        x: tuple[float, float, float],
        y: tuple[float, float, float],
        *,
        grid: bool = True,
        ticks: bool = True,
        numbers: bool = True,
        axis_color: Optional[Color] = None,
        grid_color: Optional[Color] = None,
        axis_width: float = 3.0,
        grid_width: float = 1.0,
    ) -> Drawable: ...
    def text(self, s: str) -> Drawable: ...
    def paragraph(
        self,
        s: str,
        width: float,
        *,
        align: Literal["left", "center", "right", "justify"] = "left",
        line_spacing: float = 1.2,
        font_size: Optional[float] = None,
        font_family: Optional[str] = None,
        max_lines: Optional[int] = None,
        overflow: Literal["visible", "clip"] = "clip",
    ) -> Drawable: ...
    def title(self, s: str) -> Drawable: ...
    def subtitle(self, s: str) -> Drawable: ...
    def equation(self, s: str, *, tags: Optional[dict[str, str]] = None) -> Drawable: ...
    def transform_equation(
        self,
        source: Drawable,
        target: Drawable,
        *,
        tags: Optional[Sequence[str]] = None,
        duration: float = 1.0,
    ) -> None: ...
    def expand_equation(
        self,
        source: Drawable,
        target: Drawable,
        *,
        tag: str,
        duration: float = 1.0,
    ) -> None: ...
    def replace_term(
        self,
        source: Drawable,
        target: Drawable,
        *,
        tag: str,
        target_tag: Optional[str] = None,
        duration: float = 1.0,
    ) -> None: ...
    def step_equation(
        self,
        source: Drawable,
        target: Drawable,
        *,
        duration: float = 1.0,
    ) -> None: ...
    def focus_equation(
        self,
        equation: Drawable,
        tags: Sequence[str],
        *,
        duration: float = 1.0,
        dim_opacity: float = 0.25,
    ) -> None: ...
    def brace_label(self, equation: Drawable, tag: str, label: str, *, above: bool = False, duration: float = 0.6) -> None: ...
    def annotate_tag(
        self, equation: Drawable, tag: str, label: str, *, offset: tuple[float, float] = (120.0, 80.0), duration: float = 0.6
    ) -> None: ...
    def image(
        self,
        path: str,
        *,
        width: Optional[float] = None,
        height: Optional[float] = None,
        fit: str = "contain",
        crop: Optional[tuple[float, float, float, float]] = None,
    ) -> Drawable: ...
    def svg(self, path: str) -> Drawable: ...
    def camera_pan_to(self, x: float, y: float, duration: float = 1.0) -> None: ...
    def camera_zoom_to(self, zoom: float, duration: float = 1.0) -> None: ...
    def camera_frame_to(self, target: Drawable, margin: float = 40.0, duration: float = 1.0) -> None: ...
    def camera_rotate_to(self, angle: float, duration: float = 1.0) -> None: ...
    def camera_follow(self, target: Drawable, duration: float = 1.0) -> None: ...
    def camera_shake(self, amplitude: float = 12.0, frequency: float = 8.0, duration: float = 0.5) -> None: ...
    def group(self, members: Sequence[Drawable]) -> Drawable: ...
    def segment(self, name: str, transition: Optional[Transition] = None) -> int: ...
    def link(self, from_: int, to: int, transition: Transition) -> None: ...
    def wait(self, d: float) -> None: ...
    def play(self, anims: Sequence[Anim], lag: Optional[float] = None) -> None: ...
    def slide(self) -> None: ...
    def fade_out_all(self, d: float) -> None: ...
    def render(self) -> None: ...
    def export(self, path: str, fps: Optional[int] = None) -> None: ...
    def snapshots(self, directory: str, times: Sequence[float]) -> int: ...
    # Reactive objects
    def value_tracker(self, initial: float) -> ValueTracker: ...
    def point_on_curve(self, curve: Drawable, tracker: ValueTracker) -> Drawable: ...
    def tangent_on_curve(self, curve: Drawable, tracker: ValueTracker, length: float = 80.0) -> Drawable: ...
    def normal_on_curve(self, curve: Drawable, tracker: ValueTracker, length: float = 80.0) -> Drawable: ...
    def curvature_on_curve(self, curve: Drawable, tracker: ValueTracker, window: float = 0.02) -> Drawable: ...
    def always_redraw_arc(
        self,
        tracker: ValueTracker,
        cx: float,
        cy: float,
        radius: float,
        start_angle: float,
        sweep_scale: float = 1.0,
        sweep_offset: float = 0.0,
    ) -> Drawable: ...
    def traced_path(self, source: Drawable) -> Drawable: ...
    def tracking_line(
        self,
        from_: Drawable | tuple[float, float],
        to: Drawable | tuple[float, float],
    ) -> Drawable: ...
    def spring_between(
        self,
        from_: Drawable | tuple[float, float],
        to: Drawable | tuple[float, float],
        coils: int = 8,
        amplitude: float = 12.0,
    ) -> Drawable: ...
    def dimension_between(
        self,
        from_: Drawable | tuple[float, float],
        to: Drawable | tuple[float, float],
        offset: float,
    ) -> Drawable: ...

GOLD: Color
CORAL: Color
BLUE: Color
WHITE: Color
BLACK: Color
RED: Color
GREEN: Color
YELLOW: Color
ORANGE: Color
PURPLE: Color
PINK: Color
GRAY: Color
CYAN: Color
NAVY: Color
TEAL: Color
