from typing import Any, Callable, Generic, Literal, Sequence, TypeAlias, TypeVar, overload
from .gaanim_core import Anim, Color, Drawable, Text

MatrixTraversalOrder: TypeAlias = Literal[
    "simultaneous", "row_major", "column_major", "main_diagonal",
    "anti_diagonal", "spiral_in", "spiral_out", "random",
] | Sequence[tuple[int, int]] | Callable[[int, int], Any]
MatrixIndex: TypeAlias = int | slice | Sequence[int]

class MatrixEntry:
    """A matrix value with an optional stable morph key and local text style."""
    value: Any
    key: str | None
    style: Any | None
    def __init__(self, value: Any, key: str | None = None, style: Any | None = None) -> None: ...

class MatrixSelectionAnimation(Sequence[Anim]):
    def fill(self, color: Color) -> MatrixSelectionAnimation: ...
    def color(self, color: Color) -> MatrixSelectionAnimation: ...
    def opacity(self, value: float) -> MatrixSelectionAnimation: ...
    def scale(self, factor: float) -> MatrixSelectionAnimation: ...
    def rotate(self, radians: float) -> MatrixSelectionAnimation: ...
    def duration(self, seconds: float) -> MatrixSelectionAnimation: ...

class MatrixSelection(Sequence[Drawable]):
    """Stable, multi-object selection of matrix entries."""
    @property
    def coordinates(self) -> tuple[tuple[int, int], ...]: ...
    @property
    def values(self) -> tuple[Any, ...]: ...
    def fill(self, color: Color) -> MatrixSelection: ...
    def opacity(self, value: float) -> MatrixSelection: ...
    def animate(self, *, order: MatrixTraversalOrder = "simultaneous", stagger: float = 0.0, seed: int = 0) -> MatrixSelectionAnimation: ...
    def write(self, duration: float | None = None, *, order: MatrixTraversalOrder = "row_major", stagger: float = 0.05, seed: int = 0) -> list[Anim]: ...
    def create(self, duration: float | None = None, *, order: MatrixTraversalOrder = "row_major", stagger: float = 0.05, seed: int = 0) -> list[Anim]: ...
    def fade_in(self, duration: float | None = None, *, order: MatrixTraversalOrder = "simultaneous", stagger: float = 0.0, seed: int = 0) -> list[Anim]: ...
    def fade_out(self, duration: float | None = None, *, order: MatrixTraversalOrder = "simultaneous", stagger: float = 0.0, seed: int = 0) -> list[Anim]: ...
    def indicate(self, duration: float | None = None, *, order: MatrixTraversalOrder = "simultaneous", stagger: float = 0.0, seed: int = 0) -> list[Anim]: ...
    def wiggle(self, duration: float | None = None, *, order: MatrixTraversalOrder = "simultaneous", stagger: float = 0.0, seed: int = 0) -> list[Anim]: ...
    def offset(self, dx: float, dy: float, *, animate: float | None = None) -> MatrixSelection: ...

class Matrix(Drawable):
    """Selectable Drawable-compatible facade backed by persistent Layout v2.

    Transform, placement, styling, and animation methods are delegated to the
    root layout; inherited ``Drawable`` methods therefore preserve ``Matrix``
    as their fluent return type in static analysis.
    """
    @property
    def nrows(self) -> int: ...
    @property
    def ncols(self) -> int: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def entries(self) -> MatrixSelection: ...
    @property
    def drawable(self) -> Drawable: ...
    @property
    def row_labels(self) -> tuple[Drawable, ...]: ...
    @property
    def column_labels(self) -> tuple[Drawable, ...]: ...
    @overload
    def __getitem__(self, key: tuple[int, int]) -> Drawable: ...
    @overload
    def __getitem__(self, key: tuple[MatrixIndex, MatrixIndex]) -> MatrixSelection: ...
    def row(self, index: int) -> MatrixSelection: ...
    def column(self, index: int) -> MatrixSelection: ...
    def block(self, rows: MatrixIndex, columns: MatrixIndex) -> MatrixSelection: ...
    def diagonal(self, offset: int = 0) -> MatrixSelection: ...
    def anti_diagonal(self, offset: int = 0) -> MatrixSelection: ...
    def where(self, mask_or_predicate: Any) -> MatrixSelection: ...
    def set(self, row: int, column: int, value: Any, *, animate: float | None = None) -> Drawable: ...
    def become(self, data: Any, *, animate: float | None = 1.0) -> list[Anim]: ...
    def insert_row(self, index: int, values: Sequence[Any], *, animate: float | None = 1.0) -> list[Anim]: ...
    def remove_row(self, index: int, *, animate: float | None = 1.0) -> list[Anim]: ...
    def insert_column(self, index: int, values: Sequence[Any], *, animate: float | None = 1.0) -> list[Anim]: ...
    def remove_column(self, index: int, *, animate: float | None = 1.0) -> list[Anim]: ...
    def swap_rows(self, first: int, second: int, *, animate: float | None = 1.0) -> list[Anim]: ...
    def swap_columns(self, first: int, second: int, *, animate: float | None = 1.0) -> list[Anim]: ...
    def reorder_rows(self, order: Sequence[int], *, animate: float | None = 1.0) -> list[Anim]: ...
    def reorder_columns(self, order: Sequence[int], *, animate: float | None = 1.0) -> list[Anim]: ...
    def morph_to(self, target: Matrix, *, match: str = "auto", duration: float = 1.0, stagger: float = 0.0) -> list[Anim]: ...
    def to_sympy(self) -> Any: ...
    def add(self, other: Matrix, *, exact: bool = True, precision: int | None = None) -> MatrixDerivation[Matrix]: ...
    def subtract(self, other: Matrix, *, exact: bool = True, precision: int | None = None) -> MatrixDerivation[Matrix]: ...
    def matmul(self, other: Matrix, *, exact: bool = True, precision: int | None = None) -> MatrixDerivation[Matrix]: ...
    def hadamard(self, other: Matrix, *, exact: bool = True, precision: int | None = None) -> MatrixDerivation[Matrix]: ...
    def scale_by(self, scalar: Any, *, exact: bool = True, precision: int | None = None) -> MatrixDerivation[Matrix]: ...
    def transpose(self, *, exact: bool = True, precision: int | None = None) -> MatrixDerivation[Matrix]: ...
    def determinant(self, *, exact: bool = True, precision: int | None = None) -> MatrixDerivation[Drawable]: ...
    def inverse(self, *, exact: bool = True, precision: int | None = None) -> MatrixDerivation[Matrix]: ...
    def rank(self, *, exact: bool = True, precision: int | None = None) -> MatrixDerivation[Drawable]: ...
    def trace(self, *, exact: bool = True, precision: int | None = None) -> MatrixDerivation[Drawable]: ...
    def rref(self, *, exact: bool = True, precision: int | None = None) -> MatrixDerivation[Matrix]: ...
    def lu(self, *, exact: bool = True, precision: int | None = None) -> MatrixDerivation[tuple[Matrix, Matrix]]: ...
    def qr(self, *, exact: bool = True, precision: int | None = None) -> MatrixDerivation[tuple[Matrix, Matrix]]: ...
    def eigen(self, *, exact: bool = True, precision: int | None = None) -> MatrixDerivation[tuple[Matrix, Matrix]]: ...

T = TypeVar("T")
class MatrixStep:
    kind: str
    sources: tuple[tuple[int, int], ...]
    target: tuple[int, int] | None
    expression: str | None
class MatrixDerivation(Generic[T]):
    """Exact algebra value, visual result, and adaptive animation steps."""
    value: Any
    result: T
    steps: tuple[MatrixStep, ...]
    def animate(self, *, duration: float = 0.7, order: MatrixTraversalOrder = "row_major", stagger: float = 0.04) -> list[Anim]: ...
class MatrixAlgebraError(ValueError): ...
