#!/usr/bin/env python3
"""Generate Gaanim's built-in colormap tables from ColorSchemes.jl.

Usage:
    python tools/generate_colormaps.py /path/to/ColorSchemes.jl

The generated Rust file is intentionally checked in so Gaanim does not need a
Julia or Python dependency at build/runtime. See THIRD_PARTY_NOTICES.md for
the source and licenses of the data.
"""

from __future__ import annotations

import pathlib
import re
import sys


BLOCK = re.compile(
    r"loadcolorscheme\(:(\w+),\s*\[(.*?)\]\s*,\s*\"([^\"]+)\"",
    re.DOTALL,
)
RGB = re.compile(r"(?:Colors\.)?RGB(?:\{Float64\})?\(([^)]*)\)")
DISCRETE_SUFFIX = re.compile(r"(?:10|25|50|100|S)$")
CATEGORICAL = {"tab10", "tab20", "tab20b", "tab20c"}


def parse(root: pathlib.Path) -> list[tuple[str, str, bool, list[tuple[int, int, int]]]]:
    maps: dict[str, tuple[str, str, bool, list[tuple[int, int, int]]]] = {}
    for source in sorted((root / "ColorSchemes" / "data").glob("*.jl")):
        text = source.read_text(encoding="utf-8")
        for match in BLOCK.finditer(text):
            name, body, category = match.groups()
            if category == "matplotlib":
                public_category = "matplotlib"
            elif category == "scientific colour-maps (crameri)":
                if DISCRETE_SUFFIX.search(name):
                    continue
                public_category = "scientific"
            else:
                continue
            colors = []
            for rgb in RGB.findall(body):
                values = [float(value.strip()) for value in rgb.split(",")[:3]]
                colors.append(tuple(round(max(0.0, min(1.0, value)) * 255) for value in values))
            if len(colors) < 2:
                raise RuntimeError(f"{name} has fewer than two parsed colors")
            maps[name.lower()] = (name, public_category, name in CATEGORICAL, colors)
    return sorted(maps.values(), key=lambda item: (item[1], item[0].lower()))


def rust_identifier(name: str) -> str:
    return "CM_" + re.sub(r"[^A-Za-z0-9]", "_", name).upper()


def generate(maps: list[tuple[str, str, bool, list[tuple[int, int, int]]]], revision: str) -> str:
    lines = [
        "// @generated by tools/generate_colormaps.py; do not edit by hand.",
        f"// Source: JuliaGraphics/ColorSchemes.jl revision {revision}.",
        "",
    ]
    for name, _category, _categorical, colors in maps:
        lines.append(f"static {rust_identifier(name)}: &[[u8; 3]] = &[")
        for start in range(0, len(colors), 8):
            chunk = colors[start : start + 8]
            rendered = ", ".join(f"[{r}, {g}, {b}]" for r, g, b in chunk)
            lines.append(f"    {rendered},")
        lines.append("];\n")
    lines.append("pub(crate) static BUILTINS: &[BuiltinColorMap] = &[")
    for name, category, categorical, _colors in maps:
        lines.append(
            "    BuiltinColorMap { "
            f'name: "{name}", category: "{category}", categorical: {str(categorical).lower()}, '
            f"colors: {rust_identifier(name)} "
            "},"
        )
    lines.append("];\n")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: generate_colormaps.py /path/to/ColorSchemes.jl")
    root = pathlib.Path(sys.argv[1]).resolve()
    head = (root / ".git" / "refs" / "heads" / "master").read_text().strip() if (root / ".git" / "refs" / "heads" / "master").exists() else "unknown"
    output = pathlib.Path(__file__).resolve().parents[1] / "crates" / "gaanim_core" / "src" / "colormap_data.rs"
    output.write_text(generate(parse(root), head), encoding="utf-8")


if __name__ == "__main__":
    main()
