[package]
name = "docs"
version = "0.1.0"
edition = "2024"

[dependencies]
typst-kit = {git = "https://github.com/typst/typst", features = ["http-server", "datetime", "timer", "emit-diagnostics", "bundle", "watcher"]}
typst = {git = "https://github.com/typst/typst" }
typst-html = {git = "https://github.com/typst/typst" }
typst-utils = {git = "https://github.com/typst/typst" }
clap = { version = "4.6.1", features = ["derive"] }
