#context asset(stdx.config.asset-base + "script.js", read("script.js"))
#context asset(stdx.config.asset-base + "hero.js", read("hero.js"))

// Search index: hand-written reference entries plus the full typed stub.
#context asset(
  stdx.config.asset-base + "api-index.json",
  "{\"documented\":"
    + json.encode(query(<api-entry-meta>).map(meta => meta.value), pretty: false)
    + ",\"symbols\":"
    + stdx.python-api()
    + "}",
)

#context asset(
  stdx.config.asset-base + "base.css",
  read("base.css").replace(
    "url(\"/assets/fonts",
    "url(\"fonts",
  ),
)

#let fonts = (
  "Aleo-Italic-VariableFont.ttf",
  "Aleo-VariableFont.ttf",
  "VictorMono-Italic-VariableFont.ttf",
  "VictorMono-VariableFont.ttf",
  "NewCMMath-Regular.otf",
)

#context for filename in fonts {
  let data = read("fonts/" + filename, encoding: none)
  asset(stdx.config.asset-base + "fonts/" + filename, data)
}

// Generated by tools/generate_brand.py.
#let brand = (
  "favicon.ico",
  "apple-touch-icon.png",
  "gaanim-icon.svg",
  "gaanim-icon-512.png",
  "gaanim-logo.svg",
  "gaanim-logo-dark.svg",
  "gaanim-logo-mono.svg",
  "gaanim-symbol.svg",
  "gaanim-symbol-dark.svg",
  "gaanim-social.png",
)

#context for filename in brand {
  let data = read("brand/" + filename, encoding: none)
  asset(stdx.config.asset-base + "brand/" + filename, data)
}

#context {
  let pairs = query(<metadata-asset>).map(meta => meta.value)
  let seen = (:)
  for pair in pairs {
    let path = pair.at(0)
    while path.starts-with("../") {
      path = path.slice(3)
    }
    if path in seen { continue }
    seen.insert(path, true)
    asset(path, pair.at(1))
  }
}
